### ISSUE TITLE
stickr_get() does not automatically choose logo.png

### ISSUE THREAD

**Issue by rossellhayes** [akgold/stickr#3]
The stickr_get() function displays a message when `man/figures` contains multiple files that start with "logo" rather than automatically grabbing `logo.png`.

Maybe this is a sign that I need to consider reorganizing my repository, but stickr_get() fails on my package [nombre](http://github.com/rossellhayes/nombre) because `man/figures` contains some artifacts from the process of creating the logo.
You can see the reprex below.

I'd be happy to provide a pull request if you agree that "logo.png" should be preferred if `man/figures` contains multiple files.

``` r
stickr::stickr_get("nombre")
#> Error in stickr_filename(name, repo, path): Multiple filenames found, provide *one* of these to filename argument: logo.png, logo.pptx, logo_old.png, logo_old.pptx
```

<sup>Created on 2020-07-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by alexkgold** [comment]
Hi @rossellhayes, 

Thanks for the feedback! This is currently expected behavior, but maybe not ideal. Definitely open to changing. 

Right now, if there are multiple potential logo files detected, `stickr_get` throws an error with the potential options. 

For some packages, the `logo.png` is out-of-date, and the actual logo is something like `logo-new.png`, so I think it's important to let users know if multiple files are found in the `man/figures` folder, but an error is probably too strict if `logo.png` is there. 

Probably a better behavior is to get `logo.png` if available, message or warn that there are other files there, and only fail if there's no `logo.png`. Does that sounds desirable?

**Comment by alexkgold** [comment]
@rossellhayes -- I've added the `nombre` package as a test case and implemented what I suggested above. You can test from the `logo_png` branch and see if it matches expectations. Let me know what you think! Thanks!

**Comment by rossellhayes** [comment]
The test branch works perfectly for me, but I hadn't considered the cases you raised where logo.png may be an outdated logo. One possibility could be checking if any of the image files appear in `man/*-package.Rd` and/or `README.Rmd`, but maybe that's adding more complexity than is necessary?

I'd be happy to work on a pull request if you'd be interested.
